### ISSUE TITLE
buffers I don't know what it is

### ISSUE THREAD

**Issue by 912807862** [KhronosGroup/glTF-Tutorials#21]
Hello! 

 "buffers" : [
    {
      "uri" : "data:application/octet-stream;base64,AAABAAIAAAAAAAAAAAAAAAAAAAAAAIA/AAAAAAAAAAAAAAAAAACAPwAAAAA=",
      "byteLength" : 44
    }
  ],

What's this uri ？ I don't know how to generate this binary through data.

**Comment by lexaknyazev** [comment]
As [described in the spec](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#uris), this is a Data URI defined by [RFC 2397](https://tools.ietf.org/html/rfc2397).

**Comment by 912807862** [comment]
@lexaknyazev Thank you. Let me see.

**Comment by 912807862** [comment]
@lexaknyazev I gave up the gltf format.   I first converted to obj format, and then obj to gltf

**Comment by javagl** [comment]
When the URI starts with `data:application/octet-stream;base64,`, then this is called a "data URI". You can read more about it at https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs 

In order to read the binary data from this URI, you have to look at the part that starts after `base64,`. Here, the data is `"AAABAAIAAAAAAAAAAAAAAAAAAAAAAIA/AAAAAAAAAAAAAAAAAACAPwAAAAA"`. 

Depending on the programming language that you are using, there are different ways to decode this data. If you are using JavaScript, then you will use the `atob` function, which is explained at https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/atob . More information about encoding/decoding base64 is available at https://developer.mozilla.org/en-US/docs/Web/API/WindowBase64/Base64_encoding_and_decoding

There are sites that allow you to encode/decode strings online. One of the first results that I found was https://cryptii.com/base64-to-hex , but there are other, similar sites. When you enter the string 

    AAABAAIAAAAAAAAAAAAAAAAAAAAAAIA/AAAAAAAAAAAAAAAAAACAPwAAAAA

at this site, it will be decoded to 

    00 00 01 00 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 80 3f 00 00 00 00 00 00 00 00 00 00 00 00 00 00 80 3f 00 00 00 00

This is the hexadecimal representation of the data that is then written into the glTF `buffer`. 

Does this answer your question?

**Comment by 912807862** [comment]
@javagl What about Java syntax?

**Comment by javagl** [comment]
@912807862  Can you elaborate this question?  There are classes for Base64 conversion in the standard Java SDK: https://docs.oracle.com/javase/8/docs/api/java/util/Base64.html

**Comment by cx20** [comment]
@javagl BTW, it seems that two types of Data URIs are used in the Tutorial example. It is `octet-stream` and `gltf-buffer`. As a simple question, is there a meaning to use something differently?

|Example Name         |Data URI                            |
|:--------------------|:-----------------------------------|
|[A Minimal glTF File](https://github.com/KhronosGroup/glTF-Tutorials/blob/master/gltfTutorial/gltfTutorial_003_MinimalGltfFile.md)    |data:application/octet-stream;base64|
|[A Simple Animation](https://github.com/KhronosGroup/glTF-Tutorials/blob/master/gltfTutorial/gltfTutorial_006_SimpleAnimation.md)     |data:application/octet-stream;base64|
|[Simple Meshes](https://github.com/KhronosGroup/glTF-Tutorials/blob/master/gltfTutorial/gltfTutorial_008_SimpleMeshes.md)             |data:application/octet-stream;base64|
|[A Simple Material](https://github.com/KhronosGroup/glTF-Tutorials/blob/master/gltfTutorial/gltfTutorial_011_SimpleMaterial.md)       |data:application/octet-stream;base64|
|[A Simple Texture](https://github.com/KhronosGroup/glTF-Tutorials/blob/master/gltfTutorial/gltfTutorial_013_SimpleTexture.md)         |data:application/gltf-buffer;base64|
|[Simple Cameras](https://github.com/KhronosGroup/glTF-Tutorials/blob/master/gltfTutorial/gltfTutorial_015_SimpleCameras.md)           |data:application/octet-stream;base64|
|[A Simple Morph Target](https://github.com/KhronosGroup/glTF-Tutorials/blob/master/gltfTutorial/gltfTutorial_017_SimpleMorphTarget.md)|data:application/gltf-buffer;base64|
|[Simple Skin](https://github.com/KhronosGroup/glTF-Tutorials/blob/master/gltfTutorial/gltfTutorial_019_SimpleSkin.md)                 |data:application/gltf-buffer;base64|

**Comment by emackey** [comment]
@cx20 There's no difference.  Originally we put it in a `.bin` file, with MIME type of `application/octet-stream`.  But that extension and MIME type are generic, used for any sort of binary blobs, not just glTF.  So there was a desire to rename it to something else.  The suggested new MIME type is `application/gltf-buffer`, and I proposed a new file extension as well.

Some of the reasoning for the rename is listed in https://github.com/KhronosGroup/glTF/issues/944, and a proposal for the change is in https://github.com/KhronosGroup/glTF/pull/1180.

**Comment by javagl** [comment]
@emackey So there was some overlap, I asked about this a few seconds ago in the other issue. 

IMHO, there should be a clear statement in the spec about whether to use `gltf-buffer` or `octet-stream` in data URIs. (Or does this really not matter at all for these "internal" buffers?)

**Comment by emackey** [comment]
For the choice between JPG vs PNG, a simple MIME type will tell you which decoder to use to get the image data out of a base-64 encoded URI with no filename and no file extension.  But for glTF buffers to be readable you need that full list of accessors, as the MIME type on its own can't explain it.  So the choice of internal MIME type for buffers doesn't seem to matter as much so long as readers don't break.

Let's merge this discussion with https://github.com/KhronosGroup/glTF/issues/944.

**Comment by cx20** [comment]
@emackey I understood that both Data URIs can be used.
However, when examining some glTF Exporters, it seems that `octet-stream` is used instead of `gltf-buffer`. 
I think that `gltf-buffer` is not widely known to glTF developers.

|Exporter Name|Data URI|
|:----------------|:-------------------|
|[three.js glTF Exporetr](https://github.com/mrdoob/three.js/blob/r99/examples/js/exporters/GLTFExporter.js#L1771)|application/octet-stream|
|[Babylon.js glTF Exporter](https://github.com/BabylonJS/Babylon.js/blob/master/dist/preview%20release/serializers/babylon.glTF2Serializer.js#L672)|application/octet-stream|
|[Blender glTF Exporter](https://github.com/KhronosGroup/glTF-Blender-IO/blob/master/addons/io_scene_gltf2/io/exp/gltf2_io_buffer.py#L57)|application/octet-stream|

**Comment by emackey** [comment]
@cx20 Yes, I think that's because the issue in the specification repo was never fully resolved.  We were waiting for the official IANA registration of `gltf-buffer` before updating the spec to recommend it, and we're waiting for the spec update before changing any software.

Currently it seems the discussion is resuming in the spec repo.  If we can get some consensus there, then the wording of the spec will be changed to match the new agreement, and once that wording change is merged, then we can file issues on the exporters to update their output.

I don't want to move too quickly on this.  The glTF ecosystem seems to be going along fine with the existing `octet-stream` MIME type on the buffer.  The argument for switching it doesn't feel particularly strong to me, while the risks seem pretty large.  I'm just not completely sold on the benefits of this change.

**Comment by javagl** [comment]
Assuming that the basic question is answered: The `octet-stream` vs. `gltf-buffer` question has recently been addressed in https://github.com/KhronosGroup/glTF-Sample-Models/issues/244 , and according to the comment there and the updated spec (via https://github.com/KhronosGroup/glTF/pull/1877/commits/555c4094c13574c2b1ee325fedeef33e6f1ef159 ) both options are valid. So I think it is OK to close this here.
