### ISSUE TITLE
SimpleSkin sample model doesn't match tutorial

### ISSUE THREAD

**Issue by emackey** [KhronosGroup/glTF-Tutorials#44]
The [SimpleSkin](https://github.com/KhronosGroup/glTF-Tutorials/blob/master/gltfTutorial/gltfTutorial_019_SimpleSkin.md#a-simple-skin) tutorial model doesn't quite match some of the explanations and [diagrams in skinning](https://github.com/KhronosGroup/glTF-Tutorials/blob/master/gltfTutorial/gltfTutorial_020_Skins.md#the-skin).

Specifically, the sample model places a `translation` on node index 1, which is actually joint 0, the parent joint.  It places a `rotation` but not a `translation` on node 2, joint 1, which is the only child joint.

This means the parent joint is moved to Y + 1, and the child joint is co-located with the parent joint.  The sample model still works, but only because the parent joint never moves, its only job is to hold its vertices in place.

Also, separate from the above, at some point we made the decision to zero out the first two lines of `JOINTS_0` (to silence a validation warning about zero weights on non-zero joints), and some of the wording needs to be updated to reflect what happened there.

**Comment by foxiler** [comment]
The model works because for both joints the `inverseBindMatrices` tanslate the model by -0.5 on the X axis and -1 on the Y axis.

This indicates that the model need to be translated by 1 on the Y axis to be correctly placed. If the parent joints move, the model will follow it without issue.

That said, I think it is more intuitive to place the `translation` on the joint 1 and change the `inverseBindMatrices` of the joint 0 to  this:

```
1.0   0.0   0.0   -0.5
0.0   1.0   0.0    0.0
0.0   0.0   1.0    0.0
0.0   0.0   0.0    1.0
````

I also take this opportunity to raise another problem on these pages.

The `inverseBindMatrices` on this page should be

```
1.0   0.0   0.0   -0.5
0.0   1.0   0.0   -1.0
0.0   0.0   1.0    0.0
0.0   0.0   0.0    1.0
```

In addition, the images 20b, 20c and 20d should be change to place the origin and the joints at the correct location. For exemple, the first image of 20c should be something like this:

![image](https://user-images.githubusercontent.com/43665229/102517375-3db9ff00-4090-11eb-9d63-b2a1e6e48c74.png)

But doing these changes will make the tutorial harder to understand, thus I think it is best to change the model.
The translation on joint 0 should be moved to joint 1, the position of the vertices should be translated by -0.5 on the X axis (the actual position are from (0, 0, 0) to (1, 2, 0), the translated position are from (-0.5, 0, 0) to (0.5, 2, 0))  and the `inverseBindMatrices` should be changed accordingly.

With these change, the model will truly reflect what we see on the images.

**Comment by javagl** [comment]
There is a pending update for this model, c.f. https://github.com/KhronosGroup/glTF-Tutorials/pull/41 . This specific model causes a remarkable amount of issues - hope we get this ironed out at some point...

**Comment by emackey** [comment]
@foxiler I think you're on the right track here.  The original (un-edited) diagram shows how it should ideally work, and I think it was just a mistake that crept into an otherwise carefully hand-crafted sample, where the Y axis translation was applied to the wrong joint, but that joint never moves so it doesn't impact the resulting animation.  Would you be willing to put together a PR?
