### ISSUE TITLE
Minor readability issue - image 18b

### ISSUE THREAD

**Issue by tim-rex** [KhronosGroup/glTF-Tutorials#73]
I was a little confused understanding the logic of animated morph targets..

[https://github.com/KhronosGroup/glTF-Tutorials/blob/master/gltfTutorial/gltfTutorial_018_MorphTargets.md](https://github.com/KhronosGroup/glTF-Tutorials/blob/master/gltfTutorial/gltfTutorial_018_MorphTargets.md)

The blend weight table logically reads left to right for the two morph targets.

Where image 18b shows the working calculation of the blended vertex (at t=1.25) it lists the second morph targets calculation (green) above the first morph target calculation (red)

It does so without showing any working for the effective blend weights themselves at t=1.25, which can be confusing for the reader if they expect to see the calculation written in morph target order.

**Comment by javagl** [comment]
Just to confirm: The Image 18b contains the computation
```
         ( 0.5,  0.5,  0.0)
+ 1.0  * ( 1.0,  1.0,  0.0)
+ 0.25 * (-1.0,  1.0,  0.0)
=        ( 1.25, 1.75, 0.0)
```
and the question is where the factors `1.0` and `0.25` come from, is that correct? 

I agree that it could make sense to _swap_ the rows `+ 1.0...` and `+ 0.25...` (and I'm not sure why I wrote them in this order right now...). Do you think that this could be sufficient to avoid the confusion?

Otherwise, some details could be added. Maybe by some additional statement in the preceding text, **roughly** like that:

> At the time stamp 1.25, the weights for the morph targets are computed by the animation sampler (maybe link to https://github.com/KhronosGroup/glTF-Tutorials/blob/master/gltfTutorial/gltfTutorial_007_Animations.md#animation-samplers here) as follows: 
> The weight for morph tarrget 0 (red) is (0.0 + 0.25 * (1.0 - 0.0)) = 0.25
> The weight for morph tarrget 1 (green) is (1.0 + 0.25 * (1.0 - 1.0)) = 1.0

But that might be a bit too much detail here (and therefore, potentially confusing), given that the concept of computing animated values with a sampler is already explained with an example in the linked section.

**Comment by tim-rex** [comment]
Thanks Marco. I think it’s probably sufficient to swap the two rows. While it took me longer than I care to admit to realise this was the source of my confusion, once I realised everything made perfect sense.
