### ISSUE TITLE
Where should joint matrices be stored?

### ISSUE THREAD

**Issue by 3dportable** [KhronosGroup/glTF-Tutorials#81]
in which class is it correct to store jointMatrices collections? 
If I understood correctly, Skin is not suitable because each meshNode can have its own global transformations. Then should jointMatrices be stored for each Mesh or its Node to be passed to the shader?

**Comment by javagl** [comment]
You should keep in mind the semantics of what is represented in a glTF asset. For example: The joint matrices are not stored in the glTF _directly_. They are computed from the information that is contained in the glTF, taking into account the _structure_ and _relationships_ of the elements in the glTF. 

When you have classes like `Mesh`, `Skin` and `Node` that _roughly_ correspond to the elements in a glTF, then you would probably not store any `List<Matrix> jointMatrices` in the `Mesh` class. You would also not store it in the `Skin` class. You _might_ store it in the `Node` class, because that's where all the information that is required for computing the joint matrices comes together. But you might very well "encapsulate" this part in a class that is _specific_ for rendering. This might be something like a `RenderedMesh`, maybe with specifiaizations like `RenderedSkinnedMesh` or so. 

This is probably related to https://github.com/KhronosGroup/glTF-Tutorials/issues/80#issuecomment-1437565043 . In any case, it sounds like a _very_ specific question about the class design of a library that is supposed to load or render glTF. As such, there is no _single, 'true' answer_, and I'd recommend looking at other glTF libraries to see how they solved this. (This does not mean that you'd have to take the same approach - but it might make you aware of some caveats...)

**Comment by 3dportable** [comment]
ok, thanks
